post_install() {
    post_upgrade
}

post_upgrade() {
    cp /etc/krathalan/dict/dictd.conf /etc/dict/dictd.conf
    cp /etc/krathalan/issue /etc/issue
    cp /etc/krathalan/makepkg.conf /etc/makepkg.conf
    cp /etc/krathalan/pacman.conf /etc/pacman.conf
    cp /etc/krathalan/sudoers /etc/sudoers
    cp /etc/krathalan/ssh/ssh_config /etc/ssh/ssh_config
    cp /etc/krathalan/ssh/sshd_config /etc/ssh/sshd_config
}
