post_install() {
    post_upgrade
}

post_upgrade() {
    cp /etc/krathalan/conf.d/wireless-regdom /etc/conf.d/wireless-regdom
    cp /etc/krathalan/makepkg.conf /etc/makepkg.conf
    cp /etc/krathalan/makepkg.conf /var/lib/makechrootpkg/root/etc/makepkg.conf
    cp /etc/krathalan/pacman.conf /etc/pacman.conf
    cp /etc/krathalan/pacman.d/mirrorlist /etc/pacman.d/mirrorlist
    cp /etc/krathalan/sudoers /etc/sudoers
}
