[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-c = "serifless"
capital-d = "standard-unilateral-serifed"
capital-g = "toothed-serifless-hooked"
capital-i = "short-serifed"
capital-q = "crossing"
capital-s = "serifless"
capital-u = "toothed-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless-with-horizontal-crossbar"
a = "single-storey-earless-corner-tailed"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "tailed"
g = "single-storey-earless-corner"
i = "flat-tailed"
j = "serifless"
k = "curly-serifless"
l = "tailed-serifed"
m = "tailed-top-left-serifed"
n = "tailed-serifless"
q = "diagonal-tailed-serifless"
t = "bent-hook"
u = "tailed-serifless"
v = "curly-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "straight-serifless-with-horizontal-crossbar"
lower-iota = "zshaped"
lower-lambda = "straight-turn"
lower-xi = "flat-top"
cyrl-capital-ze = "bilateral-serifed"
cyrl-ze = "bilateral-serifed"
zero = "slashed"
one = "no-base"
three = "flat-top-serifless"
four = "open-serifless"
six = "open-contour"
seven = "straight-serifed-crossbar"
eight = "crossing-asymmetric"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "compact"
dollar = "through"
percent = "rings-continuous-slash-also-connected"
ascii-single-quote = "straight"
question = "smooth"
micro-sign = "tailed-serifless"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700
