post_install() {
    post_upgrade
}

post_upgrade() {    
    cp /etc/krathalan/nginx/mime.types /etc/nginx/mime.types
    cp /etc/krathalan/nginx/nginx.conf /etc/nginx/nginx.conf
    
    cp /etc/krathalan/pacman.conf /etc/pacman.conf
    
    cp /etc/krathalan/postfix/main.cf /etc/postfix/main.cf
    cp /etc/krathalan/postfix/master.cf /etc/postfix/master.cf
    
    cp /etc/krathalan/ssh/sshd_config /etc/ssh/sshd_config
    cp /etc/krathalan/sudoers /etc/sudoers
}
